name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_credit_card: ^4.0.1
  intl: ^0.20.2
  collection: ^1.19.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.3


dependency_overrides:
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Burgers/
    - assets/images/Desserts/
    - assets/images/Pizzas/
    - assets/images/Salads/
    - assets/images/Sides/
    - assets/images/Drinks/