// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6eHuztJZdzKGfdXjmD9uMvaACfcKkrQ',
    appId: '1:150254870470:android:2da539110552618cc09cc7',
    messagingSenderId: '150254870470',
    projectId: 'fooddeliveryapp-59fbc',
    storageBucket: 'fooddeliveryapp-59fbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPJHcc-AP0SIsxgohpndp266mfplJ56o',
    appId: '1:150254870470:ios:548cf27e8120206fc09cc7',
    messagingSenderId: '150254870470',
    projectId: 'fooddeliveryapp-59fbc',
    storageBucket: 'fooddeliveryapp-59fbc.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6k1FxjLTsxkqv251KPzl0jDabniGOdos',
    appId: '1:150254870470:web:92451240e243df29c09cc7',
    messagingSenderId: '150254870470',
    projectId: 'fooddeliveryapp-59fbc',
    authDomain: 'fooddeliveryapp-59fbc.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-59fbc.firebasestorage.app',
    measurementId: 'G-BZCX8XRWVR',
  );

}